// resources/js/react/UiInput.jsx
import React from 'react'

export default function UiInput({
  type = 'text', name, id, label, placeholder, hint, error,
  value, onChange, required = false, disabled = false, className = '',
}) {
  const hasError = !!error
  const inputId = id || name

  return (
    <div>
      {label && (
        <label htmlFor={inputId} className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          {label}{required && <span className="text-red-500"> *</span>}
        </label>
      )}
      <input
        type={type} name={name} id={inputId} placeholder={placeholder}
        value={value} onChange={onChange} required={required} disabled={disabled}
        className={`block w-full rounded-lg border transition-colors duration-150 focus:outline-none focus:ring-2 sm:text-sm dark:bg-gray-800 ${hasError ? 'border-red-300 focus:border-red-500 focus:ring-red-500' : 'border-gray-300 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600'} ${className}`}
      />
      {hasError && <p className="mt-1 text-sm text-red-600">{error}</p>}
      {!hasError && hint && <p className="mt-1 text-sm text-gray-500">{hint}</p>}
    </div>
  )
}

// resources/js/svelte/UiInput.svelte
<script>
  export let type = 'text'
  export let name = null
  export let id = null
  export let label = null
  export let placeholder = null
  export let hint = null
  export let error = null
  export let value = ''
  export let required = false
  export let disabled = false
  $: inputId = id || name
  $: hasError = !!error
  $: inputCls = `block w-full rounded-lg border transition-colors duration-150 focus:outline-none focus:ring-2 sm:text-sm dark:bg-gray-800 ${hasError ? 'border-red-300 focus:border-red-500 focus:ring-red-500' : 'border-gray-300 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600'}`
</script>

<div>
  {#if label}<label for={inputId} class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{label}{#if required}<span class="text-red-500"> *</span>{/if}</label>{/if}
  <input {type} {name} id={inputId} {placeholder} {required} {disabled} bind:value class={inputCls} />
  {#if hasError}<p class="mt-1 text-sm text-red-600">{error}</p>{:else if hint}<p class="mt-1 text-sm text-gray-500">{hint}</p>{/if}
</div>
