// resources/js/svelte/UiFormGroup.svelte
<script>
  export let label = null
  export let htmlFor = null
  export let hint = null
  export let error = null
  export let required = false
</script>
<div class="mb-4">
  {#if label}<label for={htmlFor} class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{label}{#if required}<span class="text-red-500"> *</span>{/if}</label>{/if}
  <slot/>
  {#if error}<p class="mt-1 text-sm text-red-600">{error}</p>{:else if hint}<p class="mt-1 text-sm text-gray-500">{hint}</p>{/if}
</div>

// resources/js/vue/UiFormGroup.vue
<script setup>
defineProps({ label: String, for: String, hint: String, error: String, required: Boolean })
</script>
<template>
  <div class="mb-4">
    <label v-if="label" :for="$props.for" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{{ label }}<span v-if="required" class="text-red-500"> *</span></label>
    <slot />
    <p v-if="error" class="mt-1 text-sm text-red-600">{{ error }}</p>
    <p v-else-if="hint" class="mt-1 text-sm text-gray-500">{{ hint }}</p>
  </div>
</template>
